language: ruby
before_script:
  - cp config/database.yml.sample config/database.yml
  #- ln -nfs ./config/database.yml.sample ./config/database.yml
rvm:
  - 1.9.3
  - 1.9.2
  - rbx-18mode
  - rbx-19mode
